/*
 * generated by Xtext
 */
package ch.vorburger.xtext.example.ecoreref;

import ch.vorburger.xtext.example.ecoreref.scoping.MyDslImportedNamespaceAwareLocalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends ch.vorburger.xtext.example.ecoreref.AbstractMyDslRuntimeModule {

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(MyDslImportedNamespaceAwareLocalScopeProvider.class);
	}

}
