/*
 * generated by Xtext
 */
package ch.vorburger.xtext.XbaseOptionResolveAllConfusion;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ELRuntimeModule extends ch.vorburger.xtext.XbaseOptionResolveAllConfusion.AbstractELRuntimeModule {

}
