/*
 * generated by Xtext
 */
package ch.vorburger.xtext.XbaseOptionResolveAllConfusion.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ELUiModule extends ch.vorburger.xtext.XbaseOptionResolveAllConfusion.ui.AbstractELUiModule {
	public ELUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
