/*
 * generated by Xtext
 */
package ch.vorburger.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SerializerMultiValueBugUiModule extends ch.vorburger.xtext.ui.AbstractSerializerMultiValueBugUiModule {
	public SerializerMultiValueBugUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
