/*
* generated by Xtext
*/
package ch.vorburger.xtext.problems.crossnames.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BLangOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
