/*
 * generated by Xtext
 */
package ch.vorburger.xtext.example.ecoreref.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends ch.vorburger.xtext.example.ecoreref.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
