/*
* generated by Xtext
*/
package ch.voburger.xtext.sandbox.mydsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
