/*
 * generated by Xtext
 */
package org.xtext.example.usages;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UsagesRuntimeModule extends org.xtext.example.usages.AbstractUsagesRuntimeModule {

}
