/*
* generated by Xtext
*/
package org.xtext.example.usages.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class UsagesOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
