/*
 * generated by Xtext
 */
package ch.vorburger.xecore.ui.contentassist

import ch.vorburger.xecore.ui.contentassist.AbstractXEcoreProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XEcoreProposalProvider extends AbstractXEcoreProposalProvider {
}
