/*
 * generated by Xtext
 */
package ch.vorburger.xtext.problems.crossnames.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BLangUiModule extends ch.vorburger.xtext.problems.crossnames.ui.AbstractBLangUiModule {
	public BLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
