/*
* generated by Xtext
*/
package ch.vorburger.xtext.problems.crossnames.ui.contentassist;

import ch.vorburger.xtext.problems.crossnames.ui.contentassist.AbstractBLangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BLangProposalProvider extends AbstractBLangProposalProvider {

}
