/*
 * generated by Xtext
 */
package ch.vorburger.xtext.problems.crossnames.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ALangUiModule extends ch.vorburger.xtext.problems.crossnames.ui.AbstractALangUiModule {
	public ALangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
