/*
* generated by Xtext
*/
package org.xtext.example.usages.ui.contentassist;

import org.xtext.example.usages.ui.contentassist.AbstractUsagesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UsagesProposalProvider extends AbstractUsagesProposalProvider {

}
