/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl;

import ch.vorburger.xtext.xml.NameURISwapper;
import ch.vorburger.xtext.xml.NameURISwapperImpl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends org.eclipse.xtext.example.fowlerdsl.AbstractStatemachineRuntimeModule {

	public Class<? extends NameURISwapper> bindNameURISwapper() {
		return NameURISwapperImpl.class;
	}
	
}
