/*
 * generated by Xtext
 */
package ch.vorburger.xtext.XbaseOptionResolveAllConfusion.ui.contentassist

import ch.vorburger.xtext.XbaseOptionResolveAllConfusion.ui.contentassist.AbstractELProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ELProposalProvider extends AbstractELProposalProvider {
}
