/*
 * generated by Xtext 2.9.1
 */
package ch.vorburger.xtext.sandbox


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LearnJvmTypeStandaloneSetup extends LearnJvmTypeStandaloneSetupGenerated {

	def static void doSetup() {
		new LearnJvmTypeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
