/*
 * generated by Xtext 2.9.1
 */
package ch.vorburger.xtext.sandbox


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LearnJvmTypeRuntimeModule extends AbstractLearnJvmTypeRuntimeModule {
}
