/*
* generated by Xtext
*/
package ch.voburger.xtext.sandbox.mydsl.ui.contentassist;

import ch.voburger.xtext.sandbox.mydsl.ui.contentassist.AbstractMyDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {

}
