/*
 * generated by Xtext
 */
package ch.vorburger.xecore;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XEcoreRuntimeModule extends ch.vorburger.xecore.AbstractXEcoreRuntimeModule {

}
