/*
 * generated by Xtext
 */
package org.xtext.example.definitions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DefinitionsRuntimeModule extends org.xtext.example.definitions.AbstractDefinitionsRuntimeModule {

}
