/*
 * generated by Xtext
 */
package ch.vorburger.xtext.example.ecoreref.ui.contentassist

import ch.vorburger.xtext.example.ecoreref.ui.contentassist.AbstractMyDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
