/*
 * generated by Xtext
 */
package ch.vorburger.xtext.problems.crossnames;

import ch.vorburger.xtext.problems.crossnames.naming.BLangNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BLangRuntimeModule extends ch.vorburger.xtext.problems.crossnames.AbstractBLangRuntimeModule {

    public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return BLangNameProvider.class;
    }

}
