/*
 * generated by Xtext
 */
package ch.vorburger.xecore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XEcoreUiModule extends ch.vorburger.xecore.ui.AbstractXEcoreUiModule {
	public XEcoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
