/*
* generated by Xtext
*/
package ch.vorburger.xtext.ui.contentassist;

import ch.vorburger.xtext.ui.contentassist.AbstractSerializerMultiValueBugProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SerializerMultiValueBugProposalProvider extends AbstractSerializerMultiValueBugProposalProvider {

}
