/*
* generated by Xtext
*/
package org.xtext.example.definitions.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DefinitionsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
