/*
* generated by Xtext
*/
package org.xtext.example.definitions.ui.contentassist;

import org.xtext.example.definitions.ui.contentassist.AbstractDefinitionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DefinitionsProposalProvider extends AbstractDefinitionsProposalProvider {

}
