/*
 * generated by Xtext
 */
package ch.vorburger.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SerializerMultiValueBugRuntimeModule extends ch.vorburger.xtext.AbstractSerializerMultiValueBugRuntimeModule {

}
