/*
 * generated by Xtext
 */
package ch.voburger.xtext.sandbox.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends ch.voburger.xtext.sandbox.mydsl.AbstractMyDslRuntimeModule {

}
