/*
 * generated by Xtext
 */
package ch.vorburger.xtext.problems.crossnames;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ALangRuntimeModule extends ch.vorburger.xtext.problems.crossnames.AbstractALangRuntimeModule {

}
