/*
 * generated by Xtext
 */
package org.xtext.example.definitions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DefinitionsUiModule extends org.xtext.example.definitions.ui.AbstractDefinitionsUiModule {
	public DefinitionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
