/*
 * generated by Xtext
 */
package org.xtext.example.usages.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UsagesUiModule extends org.xtext.example.usages.ui.AbstractUsagesUiModule {
	public UsagesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
